name: "SSH Runner"
description: "Runs bash commands in remote server via SSH"
inputs:
  ssh_key:
    description: 'SSH Key'
  known_hosts:
    description: 'Known Hosts'
  commands:
    description: 'Command to run'
  env_vars:
    desription: 'Environment Variables that should be available in the remote'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ssh_key }}
    - ${{ inputs.known_hosts }}
    - ${{ inputs.commands }}
    - ${{ inputs.env_vars }}
