on: [push]

env:
  ARG1: arg1
  ARG2: arg2

jobs:
  try-ssh-commands:
    runs-on: ubuntu-latest
    name: SSH MY_TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: MY_TEST
        uses: ./
        with:
          ssh_key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
          env_vars: ${{toJSON(env)}}
          commands: |
            echo ${{ env.ARG }} > testfile2
            echo arg2 > testfile3
            echo "$1" > testfile4
