on: [push]

jobs:
  try-ssh-commans:
    runs-on: ubuntu-latest
    name: SSH MY_TEST
    steps:
      - name: MY_TEST
        uses: /ekahannes/ssh-commands@v1
        with:
          commands: |
            echo $1
