on: [push]

env:
  ARG: arg3

jobs:
  try-ssh-commands:
    runs-on: ubuntu-latest
    name: SSH MY_TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: MY_TEST
        uses: ./
        with:
          ssh_key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
          env_vars: "${{ env.ARG }} arg4"
          commands: |
            echo "$1" > testfile2
            echo "$2" > testfile3
